# Generated by Django 6.0.2 on 2026-02-16 16:59

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bid_price_per_kg',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='bid',
            name='quantity_kg',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='pickuporder',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='scraplisting',
            name='price_per_kg',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='scraplisting',
            name='quantity_kg',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('5.00'))]),
        ),
        migrations.AddConstraint(
            model_name='bid',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_kg__gt', Decimal('0.00'))), name='bid_quantity_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='bid',
            constraint=models.CheckConstraint(condition=models.Q(('bid_price_per_kg__gt', Decimal('0.00'))), name='bid_price_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='pickuporder',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gt', Decimal('0.00'))), name='order_total_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='scraplisting',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_kg__gt', Decimal('0.00'))), name='listing_quantity_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='scraplisting',
            constraint=models.CheckConstraint(condition=models.Q(('price_per_kg__gt', Decimal('0.00'))), name='listing_price_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='sellerprofile',
            constraint=models.CheckConstraint(condition=models.Q(('rating__gte', Decimal('0.00')), ('rating__lte', Decimal('5.00'))), name='seller_rating_between_0_and_5'),
        ),
    ]
