# Generated by Django 6.0.2 on 2026-02-16 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_bid_bid_price_per_kg_alter_bid_quantity_kg_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminprofile',
            name='user',
        ),
        migrations.RemoveConstraint(
            model_name='sellerprofile',
            name='seller_rating_between_0_and_5',
        ),
        migrations.RemoveField(
            model_name='buyerprofile',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='scraplisting',
            name='available_from',
        ),
        migrations.RemoveField(
            model_name='scraplisting',
            name='title',
        ),
        migrations.AlterField(
            model_name='scraplisting',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='scraplisting',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='AdminProfile',
        ),
        migrations.RemoveField(
            model_name='sellerprofile',
            name='gst_number',
        ),
        migrations.RemoveField(
            model_name='sellerprofile',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='sellerprofile',
            name='rating',
        ),
    ]
